# Generated by Django 4.1.1 on 2022-09-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='User',
            new_name='user',
        ),
    ]
